-- courses
create table public.courses (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text not null,
  image_link text not null,
  instructor bigint not null,
  free boolean not null default true,
  status bigint not null,
  constraint courses_pkey primary key (id),
  constraint courses_instructor_fkey foreign KEY (instructor) references instructors (id),
  constraint courses_status_fkey foreign KEY (status) references coursestatus (id)
) TABLESPACE pg_default;

-- coursedescriptions
create table public.coursedescriptions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  course_id bigint not null,
  header text not null,
  content text not null default '""'::text,
  constraint coursedescriptions_pkey primary key (id),
  constraint coursedescriptions_course_id_fkey foreign KEY (course_id) references courses (id)
) TABLESPACE pg_default;

-- coursematerials
create table public.coursematerials (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  type public.MaterialType not null,
  course_id bigint not null,
  constraint coursematerials_pkey1 primary key (id),
  constraint coursematerials_course_id_fkey1 foreign KEY (course_id) references courses (id)
) TABLESPACE pg_default;

-- coursedocuments
create table public.coursedocuments (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title text not null,
  link text not null,
  constraint coursematerials_pkey primary key (id),
  constraint coursedocuments_id_fkey foreign KEY (id) references coursematerials (id)
) TABLESPACE pg_default;

-- coursevideos
create table public.coursevideos (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  thumbnail_link text null,
  video_link text not null,
  title text not null,
  constraint coursevideos_pkey primary key (id),
  constraint coursevideos_id_fkey foreign KEY (id) references coursematerials (id),
  constraint coursevideos_id_fkey1 foreign KEY (id) references coursematerials (id)
) TABLESPACE pg_default;

-- coupons
create table public.coupons (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  instructor_id bigint not null,
  type public.CouponDiscountType not null,
  discount_value bigint not null default '0'::bigint,
  expiration_time timestamp with time zone not null,
  max_n_usage bigint not null default '1'::bigint,
  code text not null,
  constraint coupons_pkey primary key (id),
  constraint coupons_code_key unique (code),
  constraint coupons_instructor_id_fkey foreign KEY (instructor_id) references instructors (id),
  constraint check_value_by_type check (
    (
      (
        (type = 'ValueBased'::"CouponDiscountType")
        and (discount_value >= 0)
      )
      or (
        (type = 'PercentageBased'::"CouponDiscountType")
        and (discount_value >= 0)
        and (discount_value <= 100)
      )
    )
  )
) TABLESPACE pg_default;